identifier: k5z5c8k6vajaiat5
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: ng-boost-seo
homeFolder: C:\Users\m.zayed\Desktop\Projects\ng-boost-seo
distFolder: dist/ng-boost-seo
outDir: C:\Users\m.zayed\Desktop\Projects\ng-boost-seo\dist\static
handle404: ''
allowErrorCollect: true
